// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN97Z_2uRK1FaBwon5b8j4MMdwkNeL9dY',
    appId: '1:303252473587:web:9d6054c481c73810e91986',
    messagingSenderId: '303252473587',
    projectId: 'nfc-demo-c3e56',
    authDomain: 'nfc-demo-c3e56.firebaseapp.com',
    storageBucket: 'nfc-demo-c3e56.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-B0PdgCokzu7BCz3ck6FGNdSZBdHWLWE',
    appId: '1:303252473587:android:408be881e3a817dfe91986',
    messagingSenderId: '303252473587',
    projectId: 'nfc-demo-c3e56',
    storageBucket: 'nfc-demo-c3e56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmZ3PGInsEawIGrM7v4MSlGD29hHrM4TM',
    appId: '1:303252473587:ios:f1a457e96952b5b9e91986',
    messagingSenderId: '303252473587',
    projectId: 'nfc-demo-c3e56',
    storageBucket: 'nfc-demo-c3e56.appspot.com',
    iosBundleId: 'com.example.nfcDataLogger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmZ3PGInsEawIGrM7v4MSlGD29hHrM4TM',
    appId: '1:303252473587:ios:34befa99b2f56f6ae91986',
    messagingSenderId: '303252473587',
    projectId: 'nfc-demo-c3e56',
    storageBucket: 'nfc-demo-c3e56.appspot.com',
    iosBundleId: 'com.example.nfcDataLogger.RunnerTests',
  );
}
